USE [master]
GO

/****** Object:  Database [MUSIC_STORE]    Script Date: 08/13/2014 14:45:50 ******/
CREATE DATABASE [MUSIC_STORE] ON  PRIMARY 
( NAME = N'MUSIC_STORE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\MUSIC_STORE.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MUSIC_STORE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\MUSIC_STORE_log.LDF' , SIZE = 768KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MUSIC_STORE] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MUSIC_STORE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MUSIC_STORE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET ARITHABORT OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MUSIC_STORE] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MUSIC_STORE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MUSIC_STORE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MUSIC_STORE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MUSIC_STORE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MUSIC_STORE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MUSIC_STORE] SET  READ_WRITE 
GO

ALTER DATABASE [MUSIC_STORE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MUSIC_STORE] SET  MULTI_USER 
GO

ALTER DATABASE [MUSIC_STORE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MUSIC_STORE] SET DB_CHAINING OFF 
GO

